---
title: "Rachel's EDA"

output:
  pdf_document: default
  html_document: default
---

```{r}
data <- read.csv("data/EDA.csv")
```

```{r}
head(data)
nrow(data)
```

```{r}
# dropping datapoints with missing valus
colnames(data)
data <- subset(data, PRECARE!=99 & CIG_0!=99 & BMI!=99.9 & PWgt_R!=999  & PREVIS!=99 & WTGAIN!=99 & DBWT!=9999 & PAY!=9 & FRACE6!=9 & MEDUC!=9 & FEDUC!=9 & NO_RISKS!=9 & WTGAIN!=99 & FRACE6 !=9)
```

```{r}
data$pregnancy.length <- 12*(data$DOB_YY - data$DLMP_YY) + (data$DOB_MM - data$DLMP_MM)
data$WT.percent.gain <- data$WTGAIN / data$PWgt_R
```


```{r}
# binarize CIG_0
data$CIG_0_BIN <- ifelse(data$CIG_0 > 0,1,0)
```

EDA
NO_RISKS (9)
MRAVE6[sic] — Mother’s race recode 6
FRACE6 — Father’s race recode 6 (9)
MEDUC (9)
FEDUC (9)


```{r}
library(ggplot2)
```

```{r}
ggplot(data, aes(x=as.factor(NO_RISKS))) + geom_bar()
boxplot(DBWT ~ as.factor(NO_RISKS), data, xlab = "Birth weight vs. NO_RISKS")
```

```{r}
ggplot(data, aes(x=as.factor(MRAVE6))) + geom_bar()
boxplot(DBWT ~ as.factor(MRAVE6), data, xlab = "Birth weight vs. Mother's Race")
```


```{r}
ggplot(data, aes(x=as.factor(FRACE6))) + geom_bar()
boxplot(DBWT ~ as.factor(FRACE6), data, xlab = "Birth weight vs. Father's Race")
```



```{r}
ggplot(data, aes(x=as.factor(MEDUC))) + geom_bar()
boxplot(DBWT ~ as.factor(MEDUC), data, xlab = "Birth weight vs.Mother's Education")
```

```{r}
ggplot(data, aes(x=as.factor(FEDUC))) + geom_bar()
boxplot(DBWT ~ as.factor(FEDUC), data, xlab = "Birth weight vs. Father's Education")
```

```{r}
ggplot(data, aes(x=as.factor(RESTATUS))) + geom_bar()
boxplot(DBWT ~ as.factor(RESTATUS), data, xlab = "Birth weight vs. Residential Status")
```

```{r}
ggplot(data, aes(x=as.factor(PAY))) + geom_bar()
boxplot(DBWT ~ as.factor(PAY), data, xlab = "Birth weight vs. Payment Method")
```
MAGER & pregnancy length
```{r}
ggplot(data, aes(x = MAGER, y = pregnancy.length)) +
  geom_point(alpha = 0.3) + labs(title = "Pregnancy Length vs. Birth Weight") #+
 # theme(
  #  plot.title = element_text(size = 5, hjust = 0.5),
   # text = element_text(size = 5),
    #legend.position = "bottom"
  #)
```

PRECARE & pregnancy length
```{r}
ggplot(data, aes(x = MAGER, y = pregnancy.length)) +
  geom_point(alpha = 0.3) + labs(title = "Pregnancy Length vs. Birth Weight")
```

CIG_0 and pregnancy length
```{r}
boxplot(pregnancy.length ~ as.factor(CIG_0_BIN), data, xlab = "Cigarettes vs. Pregnancy Length")
```

BMI and pregnancy length
```{r}
ggplot(data, aes(x = BMI, y = pregnancy.length)) +
  geom_point(alpha = 0.3) + labs(title = "Pregnancy Length vs. BMI")
```

weight gain & preg length
```{r}
ggplot(data, aes(x = WT.percent.gain, y = pregnancy.length)) +
  geom_point(alpha = 0.3) + labs(title = "Pregnancy Length vs. % Weight Gain")
```

PREVIS & pregnancy length 
```{r}
ggplot(data, aes(x = PREVIS, y = pregnancy.length)) +
  geom_point(alpha = 0.3) + labs(title = "Pregnancy Length vs. # of Prenatal Visits")

```

MEDUC & PAY
```{r}

```

FEDUC & PAY

NO_RISKS & MRAVE6

NO_RISKS & FRACE6

